version: '3'

services:
  db:
    image: mcr.microsoft.com/azure-sql-edge
    
    volumes:
      - sqlsystem:/var/opt/mssql/
      - sqldata:/var/opt/sqlserver/data
      - sqllog:/var/opt/sqlserver/log
      - sqlbackup:/var/opt/sqlserver/backup

    ports:
      - "1444:1444"
    restart: always
     
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: SqlExpress!

  mvc:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:80"
      - "5001:443"
    restart: always
    environment:
      - DBHOST=db
      - DBPORT=1444
      - DBUSER=sa
      - DBPASSWORD=SqlExpress!
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup:
